version: '3'

services:
  web:
    build: .
    image: deflorator1980/web
    ports:
    - 5000:5000
    links:
    - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis